### ISSUE TITLE
dimension of mismatch when applying conv3d

### ISSUE THREAD

**Issue by SunCherry** [ciwang/cs234-policydist#1]
Hi,
  When I run the code, the bug report shows that the input of conv3d should be in the format of 5-D, but which is 4-D, can you enlighten my the reason?

**Comment by Jeiyoon** [comment]
Hi,
I ran this code and got some errors like below:

Traceback (most recent call last):
  File "/home/k4ke/distillation/natureqn_atari.py", line 42, in <module>
    model = NatureQN(env, config)
  File "/home/k4ke/distillation/core/q_learning.py", line 42, in __init__
    self.build(student=student)
  File "/home/k4ke/distillation/core/deep_q_learning.py", line 79, in build
    self.q = self.get_q_values_op(s, scope="q%d" % student, reuse=False)
  File "/home/k4ke/distillation/natureqn.py", line 38, in get_q_values_op
    conv1 = layers.conv3d(inputs=out, num_outputs=size1, kernel_size=[8,8], stride=4) #20
  File "/home/k4ke/anaconda3/envs/ddpd/lib/python3.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/home/k4ke/anaconda3/envs/ddpd/lib/python3.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1205, in convolution3d
    conv_dims=3)
  File "/home/k4ke/anaconda3/envs/ddpd/lib/python3.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/home/k4ke/anaconda3/envs/ddpd/lib/python3.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1025, in convolution
    (conv_dims + 2, input_rank))
ValueError: Convolution expects input with rank 5, got 4

**Comment by SunCherry** [comment]
> Hi,
> I ran this code and got some errors like below:
> 
> Traceback (most recent call last):
> File "/home/k4ke/distillation/natureqn_atari.py", line 42, in 
> model = NatureQN(env, config)
> File "/home/k4ke/distillation/core/q_learning.py", line 42, in **init**
> self.build(student=student)
> File "/home/k4ke/distillation/core/deep_q_learning.py", line 79, in build
> self.q = self.get_q_values_op(s, scope="q%d" % student, reuse=False)
> File "/home/k4ke/distillation/natureqn.py", line 38, in get_q_values_op
> conv1 = layers.conv3d(inputs=out, num_outputs=size1, kernel_size=[8,8], stride=4) #20
> File "/home/k4ke/anaconda3/envs/ddpd/lib/python3.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
> return func(*args, **current_args)
> File "/home/k4ke/anaconda3/envs/ddpd/lib/python3.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1205, in convolution3d
> conv_dims=3)
> File "/home/k4ke/anaconda3/envs/ddpd/lib/python3.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
> return func(*args, **current_args)
> File "/home/k4ke/anaconda3/envs/ddpd/lib/python3.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1025, in convolution
> (conv_dims + 2, input_rank))
> ValueError: Convolution expects input with rank 5, got 4

You need to change layers.conv3d to layers.conv2d, it will work
